### ISSUE TITLE
How to update the version of Safari used?

### ISSUE THREAD

**Issue by Nesh108** [gree/unity-webview#213]
Hello!

I noticed that the version of safari used by the plugin doesn't match the one on the system (I just updated Safari to 10.1). Is there a way to use the latest one?

I am asking because I need ES6 support and that comes only with the newer versions.

**Comment by KojiNakamaru** [comment]
It was simply because WebViewObject.cs set a custom user agent for debugging. I commented out that part in https://github.com/gree/unity-webview/pull/216. Please check the latest.

**Comment by Nesh108** [comment]
I meant that it is using an old safari plugin. This is because when I try to access a page which requires the latest version of safari, it doesn't work (no ES6 support).

**Comment by KojiNakamaru** [comment]
At least user agents match in my environment (macOS Sierra 10.12.5, Safari 10.1.1 (12603.2.4)):
```
Safari:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"

unity-webview:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko)
```

**Comment by KojiNakamaru** [comment]
Ah, maybe the cause is that Safari utilizes WKWebView while unity-webview utilizes WebView. Could you please try to utilize WebViewSeparated which utilizes WKWebView?

**Comment by Nesh108** [comment]
Using Webview separated make the whole editor crash...

**Comment by KojiNakamaru** [comment]
Sorry, I imported wrong modification when introducing bitmapRefreshCycle. I've fixed it in https://github.com/gree/unity-webview/pull/218.

**Comment by Nesh108** [comment]
Now it doesn't crash but it still doesn't seem to be using the latest version of Safari.

**Comment by KojiNakamaru** [comment]
At least the following simple test passes for both WebView and WebViewSeparated on Sierra.

```diff
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 44b7582..de5bf41 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -2,8 +2,29 @@
   <head>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <title>Unity WebView</title>
+    <script>
+      var supportsES6 = function() {
+        try {
+          new Function("(a = 0) => a");
+          return true;
+        }
+        catch (err) {
+          return false;
+        }
+      }();
+      window.addEventListener(
+        'load',
+        function() {
+          if (supportsES6) {
+            document.getElementById('msg').textContent = 'ES6';
+          } else {
+            document.getElementById('msg').textContent = 'not ES6';
+          }
+        });
+    </script>
   </head>
   <body>
+    <div id="msg"></div>
     <h1>Hello Unity WebView!</h1>
     <hr/>
     <p><a href="https://google.com">https://google.com</a> (for testing go/back buttons)</p>
```
