### ISSUE TITLE
android 10 and http

### ISSUE THREAD

**Issue by robertobrogi83** [gree/unity-webview#610]
Hi all,
I'm little bit confused.... 
I need open a streaming video in http but not working.

I follow your step and i override the manifest with 

`
<application
        android:label="@ref/0x7f040000"
        android:icon="@ref/0x7f030000"
        android:banner="@ref/0x7f010000"
        android:isGame="true"
		android:usesCleartextTraffic="true">
` 
and put in plugin -> android 

but when i mnake the build i have this error:

![screen](https://user-images.githubusercontent.com/73880173/97968696-4a73e380-1dbf-11eb-950e-aa491d3cc989.PNG)

Another question, i follow this discussion:
https://github.com/gree/unity-webview/issues/594

where i put the file xml?

is possible to have a step by step for work in http?

Many thanks all

**Comment by KojiNakamaru** [comment]
If you use Unity 2018.1 or newer, you don't need to manually place your custom AndroidManifest.xml. Instead, please define `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC`.

cf. https://github.com/gree/unity-webview/tree/e759356b3755e50a64edbf08387488c9df7faa95#usescleartexttraffic

**Comment by robertobrogi83** [comment]
@KojiNakamaru thanks for replay

Sorry but this point is not clear... 

bool UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC = true

#if UNITY_EDITOR
using System.Collections;
using System.IO;
using System.Text;
using System.Xml;
using UnityEditor.Android;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEditor;
using UnityEngine;

bla bla

is correct?

**Comment by KojiNakamaru** [comment]
It should be defined in Project Settings:
![image](https://user-images.githubusercontent.com/2645978/98098926-4c7a9700-1ed2-11eb-834e-3a40fc685e87.png)

**Comment by robertobrogi83** [comment]
aaaaaaaaaaa ! right thanks!!!

**Comment by jyhUVC** [comment]
still doesn't work..
are there more steps that I need to follow besides this?

**Comment by KojiNakamaru** [comment]
No, `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC` should be sufficient. For example, the sample app works correctly for http://httpbin.org/ . My environment is:
* Unity 2019.4.18f1
* Vankyo S7 (Android 9)

**Comment by jyhUVC** [comment]
Thanks for your support and the address you provided actually works.

However, when I try to open a web pdf like http://www.africau.edu/images/default/sample.pdf , this won't open it.

Is it not possible to open the pdf address?

**Comment by KojiNakamaru** [comment]
I see, it is not about http/https; android webview cannot open pdf files by default. I've fixed the code and updated binaries. Could you please try the latest?

**Comment by dragonho96** [comment]
hmm I tried but I still won't work! Also when I tried to implement this to another project, the browser won't show up either, not even the white screen. Is there a proper way to export this to other projects? Thanks

**Comment by jyhUVC** [comment]
hmm I tried the new version but it still doesn't work!

**Comment by jyhUVC** [comment]
Could you help me out on opening PDF on the web viewer? are there more steps that I need to follow?

**Comment by KojiNakamaru** [comment]
If you install Google Drive or Google PDF Viewer, a pdf should be opened by them.
