### ISSUE TITLE
Resolution problem that occurs when I see the built screen on mobile after I build it with Webgl.

### ISSUE THREAD

**Issue by jhj198988** [gree/unity-webview#859]
Currently, I am using the Unity version 2021.3.11f1 and I am testing it by build it with Webgl.
When I build with Webgl, it comes out very well when I used a pc to look at the screen, but when I use a mobile to look at the screen, there is a resolution problem.
(The picture below shows a resolution problem when I look at the screen using a mobile. The resolution is much smaller than the screen on the mobile)
![20221130_160401419](https://user-images.githubusercontent.com/54474036/204730114-4da9dbf4-a08d-4e8a-9c13-4208bfb26426.jpg)
I am currently using Unity-webview-2020 for Webgl template, and I am using Default Canvas Width, Height 1920 and 1080.
Is there a solution?

**Comment by KojiNakamaru** [comment]
Thank you for the report. #846 seemed to introduce this issue, which is now fixed by #860. Could you please try the latest?

**Comment by jhj198988** [comment]
> Thank you for the report. #846 seemed to introduce this issue, which is now fixed by #860. Could you please try the latest?
I applied the latest version, but it's still the same.
The screen I saw on the mobile after build the webgl is shown in the picture below.
![20221202_1016](https://user-images.githubusercontent.com/54474036/205193367-26432ec8-c0c6-4dfd-a77e-87c5a0b66258.jpg)

**Comment by KojiNakamaru** [comment]
Hmm, at least the sample app seems to run without such an issue. I've put adjusted sample that can be directly built for webgl with 2021.3.11f1:

https://github.com/gree/unity-webview/tree/example-for-859/sample

and [sample-webgl.zip](https://github.com/gree/unity-webview/files/10141957/sample-webgl.zip) is the build. The following is a screenshot of it running on iPhone Safari:

![image](https://user-images.githubusercontent.com/2645978/205320358-e8815808-8794-4914-b2be-d73380baabdd.png)

**Comment by jhj198988** [comment]
> Hmm, at least the sample app seems to run without such an issue. I've put adjusted sample that can be directly built for webgl with 2021.3.11f1:
> 
> https://github.com/gree/unity-webview/tree/example-for-859/sample
> 
> and [sample-webgl.zip](https://github.com/gree/unity-webview/files/10141957/sample-webgl.zip) is the build. The following is a screenshot of it running on iPhone Safari:

Problem solved.
It was solved by exporting the downloaded sample project(https://github.com/gree/unity-webview/tree/example-for-859/sample) itself and importing it into my project.
Thank you so much for your help!
